export const SET_USER_LIST = "SET_USER_LIST";
export const INPUT_SEARCH_VALUE = "INPUT_SEARCH_VALUE";
export const ON_CLICK_ADD_USER = "ON_CLICK_ADD_USER";
export const INPUT_NEW_USER_PHONE_VALUE = "INPUT_NEW_USER_PHONE_VALUE";
export const INPUT_NEW_USER_NAME_VALUE = "INPUT_NEW_USER_NAME_VALUE";
export const INPUT_NEW_USER_EMAIL_VALUE = "INPUT_NEW_USER_EMAIL_VALUE";